import { DESIGN_WIDTH, getGameViewport } from "./Layout";

const viewport = getGameViewport();

export const constant = {
  SCALE: viewport.width / DESIGN_WIDTH,
  MAX_POINT_PROGRESS: 2200,
  MOVE_LIMITS: [22, 24, 25, 27, 29, 31, 32, 34, 36],

  TEXTURE_KEY_BACKGROUND: "background",
  TEXTURE_KEY_BACK_ARROW: "back-arrow",
  TEXTURE_KEY_MUSIC: "music",
  TEXTURE_KEY_MICROPHONE: "microphone",
  TEXTURE_KEY_DISABLE_AUDIO: "disable-audio",
  TEXTURE_KEY_MOVES_FRAME: "moves-frame",
  TEXTURE_KEY_POINT_FRAME: "point-frame",
  TEXTURE_KEY_POINT_PROGRESS_FRAME: "point-progress-frame",
  TEXTURE_KEY_POINT_PROGRESS: "point-progress",
  TEXTURE_KEY_FAILED: "failed",
  TEXTURE_KEY_RETRY: "retry",
  TEXTURE_KEY_NEXT: "next",
  TEXTURE_KEY_VICTORY: "victory",
  TEXTURE_KEY_STAR: "star",
  TEXTURE_KEY_LEVEL_1: "level-1",
  TEXTURE_KEY_LEVEL_2: "level-2",
  TEXTURE_KEY_LEVEL_3: "level-3",
  TEXTURE_KEY_LEVEL_4: "level-4",
  TEXTURE_KEY_LEVEL_5: "level-5",
  TEXTURE_KEY_LEVEL_6: "level-6",
  TEXTURE_KEY_LEVEL_7: "level-7",
  TEXTURE_KEY_LEVEL_8: "level-8",
  TEXTURE_KEY_LEVEL_9: "level-9",
  TEXTURE_KEY_LEVEL_10: "level-10",
  TEXTURE_KEY_GAME_AREA_CELL: "game-area-cell",

  ITEM_INDICES: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14],
  TEXTURE_KEY_ITEM_1: "item-1",
  TEXTURE_KEY_ITEM_2: "item-2",
  TEXTURE_KEY_ITEM_3: "item-3",
  TEXTURE_KEY_ITEM_4: "item-4",
  TEXTURE_KEY_ITEM_5: "item-5",
  TEXTURE_KEY_ITEM_6: "item-6",
  TEXTURE_KEY_ITEM_7: "item-7",
  TEXTURE_KEY_ITEM_8: "item-8",
  TEXTURE_KEY_ITEM_9: "item-9",
  TEXTURE_KEY_ITEM_10: "item-10",
  TEXTURE_KEY_ITEM_11: "item-11",
  TEXTURE_KEY_ITEM_12: "item-12",
  TEXTURE_KEY_ITEM_13: "item-13",
  TEXTURE_KEY_ITEM_14: "item-14",

  TEXTURE_KEY_NPC_STATIC: "npc-static",
  ANIMATION_KEY_NPC_STATIC: "animation-npc-static",
  TEXTURE_KEY_HINT_BUBBLE: "hint-bubble",
  ANIMATION_KEY_HINT_BUBBLE: "animation-hint-bubble",
  TEXTURE_KEY_PINK_FISH: "pink-fish",
  ANIMATION_KEY_PINK_FISH: "animation-pink-fish",
  TEXTURE_KEY_FISH_4: "fish-4",
  ANIMATION_KEY_FISH_4: "animation-fish-4",
  TEXTURE_KEY_JELLYFISH: "jellyfish",
  ANIMATION_KEY_JELLYFISH: "animation-jellyfish",
  TEXTURE_KEY_DISAPPEAR: "disappear",
  BACKGROUND_MUSIC: "background-music",
  BUTTON_SOUND: "button-sound",
  DROP_SOUND: "drop-sound",
  SWAP_SOUND: "swap-sound",
  ELIMINATE_SOUND: "eliminate-sound",
};
